import { Controller, Get, UseGuards, Post, Request, Body, HttpException, Param, Query } from '@nestjs/common';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import {DatabaseService} from '../database/database.service'

function getExpiryDate(expiresIn) {
  // return the actual date/time the token expires.
  // expiresIn, from spotify, is number of seconds until it expires.
  return new Date(Date.now() + expiresIn*1000);
}

@Controller('/songData')
export class SongDataController {
  constructor(private databaseService: DatabaseService) {}

  // @UseGuards(JwtAuthGuard)
  // @Get()
  // getHello(): string {
  //   return this.appService.getHello();
  // }

  // @UseGuards(LocalAuthGuard)
  // @Post('/login')
  // async login(@Request() req) {
  //   return this.authService.login(req.user);
  // }

  @UseGuards(JwtAuthGuard)
  @Get('/:userID/last50')
  async getLast50() {

  }

  @UseGuards(JwtAuthGuard)
  @Get('/:userID/history')
  getHistory(@Param() params, @Query() query): any {
    console.log(params.userID);
    console.log(query.from);
    console.log(query.to);

    return [
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1gRNBaI4yn6wCCTvRhGWh8"
              },
              "href": "https://api.spotify.com/v1/artists/1gRNBaI4yn6wCCTvRhGWh8",
              "id": "1gRNBaI4yn6wCCTvRhGWh8",
              "name": "Don McLean",
              "type": "artist",
              "uri": "spotify:artist:1gRNBaI4yn6wCCTvRhGWh8"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/10jsW2NYd9blCrDITMh2zS"
          },
          "href": "https://api.spotify.com/v1/albums/10jsW2NYd9blCrDITMh2zS",
          "id": "10jsW2NYd9blCrDITMh2zS",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730085dd4362653ef4c54ebbeb",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020085dd4362653ef4c54ebbeb",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510085dd4362653ef4c54ebbeb",
              "width": 64
            }
          ],
          "name": "American Pie",
          "release_date": "1971",
          "release_date_precision": "year",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:10jsW2NYd9blCrDITMh2zS"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gRNBaI4yn6wCCTvRhGWh8"
            },
            "href": "https://api.spotify.com/v1/artists/1gRNBaI4yn6wCCTvRhGWh8",
            "id": "1gRNBaI4yn6wCCTvRhGWh8",
            "name": "Don McLean",
            "type": "artist",
            "uri": "spotify:artist:1gRNBaI4yn6wCCTvRhGWh8"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AL",
          "AR",
          "AT",
          "AU",
          "BA",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "BY",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HR",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "KW",
          "KZ",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MK",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "SA",
          "SE",
          "SG",
          "SI",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "UA",
          "US",
          "UY",
          "VN",
          "XK",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 516893,
        "explicit": false,
        "external_ids": {
          "isrc": "USEM38600088"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1fDsrQ23eTAVFElUMaf38X"
        },
        "href": "https://api.spotify.com/v1/tracks/1fDsrQ23eTAVFElUMaf38X",
        "id": "1fDsrQ23eTAVFElUMaf38X",
        "is_local": false,
        "name": "American Pie",
        "popularity": 76,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1fDsrQ23eTAVFElUMaf38X",
        "PlayedAt": "2019-04-27T00:06:04.000Z"
      },
      {
        "album": {
          "album_type": "compilation",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4QQgXkCYTt3BlENzhyNETg"
              },
              "href": "https://api.spotify.com/v1/artists/4QQgXkCYTt3BlENzhyNETg",
              "id": "4QQgXkCYTt3BlENzhyNETg",
              "name": "Earth, Wind & Fire",
              "type": "artist",
              "uri": "spotify:artist:4QQgXkCYTt3BlENzhyNETg"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4MgtwNYjD89Oj2km6eFRYd"
          },
          "href": "https://api.spotify.com/v1/albums/4MgtwNYjD89Oj2km6eFRYd",
          "id": "4MgtwNYjD89Oj2km6eFRYd",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2736e5689a9d09ac1fc2cba2ab0",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e026e5689a9d09ac1fc2cba2ab0",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048516e5689a9d09ac1fc2cba2ab0",
              "width": 64
            }
          ],
          "name": "September",
          "release_date": "2018-04-17",
          "release_date_precision": "day",
          "total_tracks": 15,
          "type": "album",
          "uri": "spotify:album:4MgtwNYjD89Oj2km6eFRYd"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4QQgXkCYTt3BlENzhyNETg"
            },
            "href": "https://api.spotify.com/v1/artists/4QQgXkCYTt3BlENzhyNETg",
            "id": "4QQgXkCYTt3BlENzhyNETg",
            "name": "Earth, Wind & Fire",
            "type": "artist",
            "uri": "spotify:artist:4QQgXkCYTt3BlENzhyNETg"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AL",
          "AR",
          "AT",
          "AU",
          "BA",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "BY",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HR",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "KZ",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MK",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "SA",
          "SE",
          "SG",
          "SI",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "UA",
          "US",
          "UY",
          "VN",
          "XK",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 215080,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM17800845"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7Cuk8jsPPoNYQWXK9XRFvG"
        },
        "href": "https://api.spotify.com/v1/tracks/7Cuk8jsPPoNYQWXK9XRFvG",
        "id": "7Cuk8jsPPoNYQWXK9XRFvG",
        "is_local": false,
        "name": "September",
        "popularity": 75,
        "preview_url": "https://p.scdn.co/mp3-preview/ae4aa51502978e1a866375fd9c397007c546d12a?cid=aa544564fc324b3f90ca67514e4a20d9",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:7Cuk8jsPPoNYQWXK9XRFvG",
        "PlayedAt": "2019-04-26T23:56:43.000Z"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7f8LNBVXN0h35veHrpxQFL"
              },
              "href": "https://api.spotify.com/v1/artists/7f8LNBVXN0h35veHrpxQFL",
              "id": "7f8LNBVXN0h35veHrpxQFL",
              "name": "Norman Greenbaum",
              "type": "artist",
              "uri": "spotify:artist:7f8LNBVXN0h35veHrpxQFL"
            }
          ],
          "available_markets": [
            
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7EJVbA8JDIn4uc04F1m9IU"
          },
          "href": "https://api.spotify.com/v1/albums/7EJVbA8JDIn4uc04F1m9IU",
          "id": "7EJVbA8JDIn4uc04F1m9IU",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2738ab6f530d434041ef1c8af8c",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e028ab6f530d434041ef1c8af8c",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048518ab6f530d434041ef1c8af8c",
              "width": 64
            }
          ],
          "name": "Spirit In The Sky",
          "release_date": "2001-01-01",
          "release_date_precision": "day",
          "total_tracks": 17,
          "type": "album",
          "uri": "spotify:album:7EJVbA8JDIn4uc04F1m9IU"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7f8LNBVXN0h35veHrpxQFL"
            },
            "href": "https://api.spotify.com/v1/artists/7f8LNBVXN0h35veHrpxQFL",
            "id": "7f8LNBVXN0h35veHrpxQFL",
            "name": "Norman Greenbaum",
            "type": "artist",
            "uri": "spotify:artist:7f8LNBVXN0h35veHrpxQFL"
          }
        ],
        "available_markets": [
          
        ],
        "disc_number": 1,
        "duration_ms": 242893,
        "explicit": false,
        "external_ids": {
          "isrc": "US3M50122902"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3PPDUkGHUJx2bxct6A3PBy"
        },
        "href": "https://api.spotify.com/v1/tracks/3PPDUkGHUJx2bxct6A3PBy",
        "id": "3PPDUkGHUJx2bxct6A3PBy",
        "is_local": false,
        "name": "Spirit In The Sky",
        "popularity": 0,
        "preview_url": null,
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:3PPDUkGHUJx2bxct6A3PBy",
        "PlayedAt": "2019-04-26T23:53:06.000Z"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0TqIPD4IS1w4e30R38B3vj"
              },
              "href": "https://api.spotify.com/v1/artists/0TqIPD4IS1w4e30R38B3vj",
              "id": "0TqIPD4IS1w4e30R38B3vj",
              "name": "Rupert Holmes",
              "type": "artist",
              "uri": "spotify:artist:0TqIPD4IS1w4e30R38B3vj"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/163iYwl7Kdm9ayTnD4VyfN"
          },
          "href": "https://api.spotify.com/v1/albums/163iYwl7Kdm9ayTnD4VyfN",
          "id": "163iYwl7Kdm9ayTnD4VyfN",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273af7afb5c49afd3133fa2a6c9",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02af7afb5c49afd3133fa2a6c9",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851af7afb5c49afd3133fa2a6c9",
              "width": 64
            }
          ],
          "name": "Partners In Crime",
          "release_date": "1979-01-01",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:163iYwl7Kdm9ayTnD4VyfN"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0TqIPD4IS1w4e30R38B3vj"
            },
            "href": "https://api.spotify.com/v1/artists/0TqIPD4IS1w4e30R38B3vj",
            "id": "0TqIPD4IS1w4e30R38B3vj",
            "name": "Rupert Holmes",
            "type": "artist",
            "uri": "spotify:artist:0TqIPD4IS1w4e30R38B3vj"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AL",
          "AR",
          "AT",
          "AU",
          "BA",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "BY",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HR",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "KZ",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MK",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "SA",
          "SE",
          "SG",
          "SI",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "UA",
          "US",
          "UY",
          "VN",
          "XK",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 276493,
        "explicit": false,
        "external_ids": {
          "isrc": "USMC17948997"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5IMtdHjJ1OtkxbGe4zfUxQ"
        },
        "href": "https://api.spotify.com/v1/tracks/5IMtdHjJ1OtkxbGe4zfUxQ",
        "id": "5IMtdHjJ1OtkxbGe4zfUxQ",
        "is_local": false,
        "name": "Escape (The Pina Colada Song)",
        "popularity": 75,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5IMtdHjJ1OtkxbGe4zfUxQ",
        "PlayedAt": "2019-04-26T23:49:03.000Z"
      }
    ];
  }

}
